### ISSUE TITLE
Publish amd64 images

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/build#20]
I think the experimentation with `arm64` builds may have gone a bit too far. All recent images are are `arm64` only.  Can we get the `amd64` back? Specifically the `latest` tag otherwise it will be rather annoying to make releases.

https://hub.docker.com/r/cucumber/cucumber-build/tags

**Comment by mpkorstanje** [comment]
Does look like `cucumber/cucumber-build:0.1.0@sha256:2ce049493dfadad62b78594e6728d1f85ccc5a2441b5a8b3f7a106a7bba39ec1` is still usable to make releases from for JVM.

**Comment by mattwynne** [comment]
Yes, this was a mistake on my part because I was running the publish script by hand and I am a clown sometimes.

It's [sorted for now](https://hub.docker.com/layers/cucumber/cucumber-build/latest/images/sha256-9c28fc1d9d8c4e825d66efb8d22979baecaae96a112706fd4ba3442e1f39a8b7?context=explore), but I propose #21 to reduce the chance of human error in the future.
